name: Go
on: [push]
jobs:
  windows:
      runs-on: windows-latest
      strategy:
        matrix:
          go: ['1.16']
      name: Go ${{ matrix.go }} on Windows
      env:
        name: windows
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Test Library
          run: |
            go test ./...

  macos:
      runs-on: macOS-latest
      strategy:
        matrix:
          go: ['1.16']
      name: Go ${{ matrix.go }} on MacOS
      env:
        name: mac
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Test Library
          run: |
            go test ./...

  linux:
      name: Go ${{ matrix.go }} on Ubuntu
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go: ['1.16']
      env:
        name: ubuntu
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Test Library
          run: |
            go test ./...
